version: "3"

services:
  db:
    build:
      context: .
      dockerfile: DockerfileDB
    ports:
      - 1433:1433
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passwo0RD!
      - MSSQL_PID=Developer
      - MSSQL_MEMORY_LIMIT_MB= 8192
      - MSSQL_AGENT_ENABLED=true
      - TZ=Europe/Amsterdam
  mssql-r2dbc-reactiveeventstore:
    image: mssql-r2dbc-reactiveeventstore:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db  
    volumes:
      - r2dbcdata:/var/opt/events  
volumes: 
  r2dbcdata: 