version: '2.1'

services:
  mssql-r2dbc-reactiveeventstore:
    image: mssql-r2dbc-reactiveeventstore
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - db       
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa$wo0RD!
      - MSSQL_PID=Developer
      - MSSQL_LCID=1031
      - MSSQL_COLLATION=Latin1_General_CI_AS
      - MSSQL_MEMORY_LIMIT_MB=8192
      - MSSQL_AGENT_ENABLED=true
      - TZ=Europe/Berlin
    ports:
      - 1433:1433
      - 49200:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./backup:/var/opt/mssql/backup
    restart: always   