version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passwo0RD!
      - MSSQL_PID=Developer
      - MSSQL_MEMORY_LIMIT_MB= 8192
      - MSSQL_AGENT_ENABLED=true
      - TZ=Europe/Amsterdam
    networks: 
      - r2dbcnetwork  
  mssql-r2dbc-reactiveeventstore:
    image: mssql-r2dbc-reactiveeventstore:latest
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db  
    networks: 
      - r2dbcnetwork   
    volumes:
      - r2dbcdata:/var/opt/events  
networks: 
  r2dbcnetwork:
    driver: bridge
volumes: 
  r2dbcdata: 